

<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3 class="head-dashboard"><?php echo $this->__('Condition of warehouse') ?></h3></td>
        </tr>
    </table>
</div>
<div class="dashboard-container">
    <?php echo $this->getChildHtml('store_switcher') ?>
    <table cellspacing="25" width="100%">
        <tr>
            <td width="30%">
                <?php // echo $this->getChildHtml('sales') ?>
            </td>
            <td width="70%">
                <!--<div class="entry-edit" style="border:1px solid #ccc;">
                    <?php /*echo $this->getChildHtml('diagrams') */?>
                    <?php//*/ if (is_array($this->getChild('diagrams')->getTabsIds())) : */?>
                        <div id="diagram_tab_content"></div>
                    <?php /*//endif; */?>
                    <div style="margin:20px;">
                        <?php /*echo $this->getChildHtml('totals') */?>
                    </div>
                    <div style="margin:20px;">
                        <?php /*echo $this->getChildHtml('grids') */?>
                        <div id="grid_tab_content"></div>
                    </div>
                </div>-->
            </td>
        </tr>
    </table>
</div>




