<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3 class="head-dashboard"><?php echo $this->__('Integration the module') ?></h3></td>
        </tr>
    </table>
</div>
<div class="integration-container">
	<h4>1. Shift the data from the .xlsx file (approx. 20 minutes)</h4>
    <?php echo $this->getChildHtml('offwego_button') ?>
    <div id="resultOfIntegration">
    </div>
    <br><br>

    <h4>2. Recount location's sizes. (approx. 40 seconds)</h4>
	<?php echo $this->getChildHtml('size_button') ?>
    <div id="resultOfCountingSizes">
    </div>
</div>

<script type="text/javascript">
    integration = new integrationModel('<?=$this->getUrlControllerAdmin();?>');
</script>

<style>
    #resultOfIntegration {
        margin: 20px 0px 0px 0px;
    }
</style>





