
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3 class="head-dashboard"><?php echo $this->__('New location for product') ?></h3></td>
        </tr>
    </table>
</div>
<div class="dashboard-container">
    <div class="search-line">
        <input type="text" placeholder="Start to taiping the SKY, barcode or name of product">
		<?php echo $this->getChildHtml('print1_button') ?>
        <button>Print 2</button>
    </div>
    <table cellspacing="25" width="100%">
        <tr>
            <td width="60%">
                <div class="product-information" style="background:#fafafa; padding:8px 15px;">
                     Place for information about product.
                </div>
            </td>
            <td width="40%">
                <div class="filter-newlocations">
                    <?php echo $this->getChildHtml('filter') ?>
                </div>
            </td>
        </tr>
    </table>
</div>




