<?php
    $p = $this->getProduct();
    $h = Mage::helper('swstocklocation');
?>
<table>
    <tr>
        <td width="50%">
            <div class="short-product-info">
                <input type="hidden" name="productId" value="<?=$p->getId();?>">
                <img src="http://magento.loc/media/catalog/product/<?=$p->getThumbnail();?>" >
                <ul>
                    <li>ID: <?=$p->getId();?></li>
                    <li>Name: <b><?=$p->getName();?></b></li>
                    <li>SKY: <b><?=$p->getSku();?></b></li>
                    <li>BC: <b> - <?=$p->getBarcode();?></b></li>
                </ul>
            </div>
        </td>
        <td width="50%">
			<? $arLocations = $this->getLocationsOfProduct($p->getID());
			if (count($arLocations)>0) { ?>
                <table class="listLocations" id="listLocations">
                    <thead>
                        <tr>
                            <td>Location</td>
                            <td>QTY</td>
                            <td>Correction of qty</td>
                        </tr>
                    </thead>
                    <tbody>
					<? foreach ($arLocations AS $k => $location) { ?>
                        <tr>
                            <td><?=$h->getLocationName($location['id'])?></td>
                            <td>
                                <input id="qtyDefault_<?=$location['id']?>" type="hidden" value="<?=$location['qty']?>">
                                <input
                                    id="qty_<?=$location['id']?>"
                                    type="text"
                                    value="<?=$location['qty']?>"
                                    disabled
                                    style="width: 50px;"
                                >
                            </td>
                            <td>
                                <button
                                    class="no-display"
                                    id="button_<?=$location['id']?>"
                                    onclick="newLocation.correctProdInLocation('<?=$location['id']?>','<?=$p->getId();?>');"
                                >
                                    Update
                                </button>
                                <span class="correct-checkbox" id="correct_<?=$location['id']?>" >
                                    <input
                                        type="checkbox"
                                        name="correct[<?=$location['id']?>]"
                                        onclick="newLocation.showCorrectButton('<?=$location['id']?>');"
                                        id="correct<?=$location['id']?>"
                                    >
                                    <label for="correct<?=$location['id']?>">Change</label>
                                </span>
                            </td>
                        </tr>
					<? } ?>
                    </tbody>
                </table>
			<? } ?>
            <div id="placeForNewLinkProductAndLocation">
            </div>
        </td>
    </tr>
</table>
<div class="history-movement">
    <h3>History of movement</h3>
    <ul>
        <li></li>
        <li></li>
    </ul>
</div>



<style>
    #productInformation table {
        width: 100%;
    }
    #productInformation .short-product-info {
        margin:0px 20px 0px 0px;
    }
    #productInformation .short-product-info img {
        margin: 0px 10px 0px 0px;
        height: 100px;
        width: auto;
        float: left;
    }
    #productInformation .short-product-info ul {

    }
    #productInformation .short-product-info ul li {
        margin:0px 0px 5px;
    }
    #productInformation table.listLocations {
        margin:0px 0px 20px 0px;
    }

    #productInformation .history-movement {
        margin: 20px 0px 0px 0px;
    }

    .correct-checkbox {
        float: right;
    }
</style>

