
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3 class="head-dashboard"><?php echo $this->__('New location for product') ?></h3></td>
        </tr>
    </table>
</div>
<div class="dashboard-container">
    <div class="search-line">
        <input type="text" placeholder="Start to taiping the SKY, barcode or name of product" id="searchLine">
		<?php echo $this->getChildHtml('search_button') ?>
        <?php echo $this->getChildHtml('print1_button') ?>
		<?php echo $this->getChildHtml('print2_button') ?>
    </div>
    <table cellspacing="25" width="100%">
        <tr>
            <td width="60%">
                <div class="product-information" id="productInformation">
                     Place for information about product.<br/>
                </div>
            </td>
            <td width="40%">
                <div class="filter-newlocations">
                    <?php echo $this->getChildHtml('filter') ?>
                </div>
            </td>
        </tr>
    </table>
</div>

<script type="text/javascript">
    <?php //echo $this->getId() ?>
    newLocation = new newLocationModel('<?=$this->getUrlControllerAdmin();?>');
</script>






