
<div id="dialog-form" style="display:none;">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <style>
        label, input { display:block; }
        input.text { margin-bottom:12px; width:95%; padding: .4em; }
        fieldset { padding:0; border:0; margin-top:25px; }
        h1 { font-size: 1.2em; margin: .6em 0; }
        div#users-contain { width: 350px; margin: 20px 0; }
        div#users-contain table { margin: 1em 0; border-collapse: collapse; width: 100%; }
        div#users-contain table td, div#users-contain table th { border: 1px solid #eee; padding: .6em 10px; text-align: left; }
        .ui-dialog .ui-state-error { padding: .3em; }
        .validateTips { border: 1px solid transparent; padding: 0.3em; }
        #dialog-form fieldset legend {
            height: auto;
            line-height: 1.1;
            overflow: initial;
            visibility: visible;
            width: auto;
            margin-bottom: 5px;
        }
    </style>
    <form>
        <fieldset id="warehouses">
            <legend>Warehouse(s): </legend>
            <label for="warehouse-M">M</label>
            <input class="checkboxInput" type="checkbox" name="warehouse[]" value="M" id="warehouse-M">
            <label for="warehouse-O">O</label>
            <input class="checkboxInput" type="checkbox" name="warehouse[]" value="O" id="warehouse-O">
            <label for="warehouse-P">P</label>
            <input class="checkboxInput" type="checkbox" name="warehouse[]" value="P" id="warehouse-P">
            <label for="warehouse-L">L</label>
            <input class="checkboxInput" type="checkbox" name="warehouse[]" value="L" id="warehouse-L">
        </fieldset>

        <fieldset id="rows">
            <legend>Row(s): </legend>
            <label for="row-1">1</label>
            <input class="checkboxInput" type="checkbox" name="row[]" value="1" id="row-1">
            <label for="row-2">2</label>
            <input class="checkboxInput" type="checkbox" name="row[]" value="2" id="row-2">
            <label for="row-3">3</label>
            <input class="checkboxInput" type="checkbox" name="row[]" value="3" id="row-3">
            <label for="row-4">4</label>
            <input class="checkboxInput" type="checkbox" name="row[]" value="4" id="row-4">
        </fieldset>

        <fieldset id="bins">
            <legend>Bin(s): </legend>
            <label for="bin-1">1</label>
            <input class="checkboxInput" type="checkbox" name="bin[]" value="1" id="bin-1">
            <label for="bin-2">2</label>
            <input class="checkboxInput" type="checkbox" name="bin[]" value="2" id="bin-2">
            <label for="bin-3">3</label>
            <input class="checkboxInput" type="checkbox" name="bin[]" value="3" id="bin-3">
            <label for="bin-4">4</label>
            <input class="checkboxInput" type="checkbox" name="bin[]" value="4" id="bin-4">
        </fieldset>

        <fieldset>
            <label for="shelves">Shelf(shelves):</label>
            <input type="text" id="shelves" readonly style="border:0; color:#f6931f; font-weight:bold;">
            <div id="shelves-range"></div>
        </fieldset>

        <fieldset id="dimension">
            <legend>Size of location(s): </legend>
            <label for="dimensionNull">I don't care</label>
            <input class="radioInput" type="radio" name="dimension" value="null" id="dimensionNull" checked>
            <label for="dimensionSmall">Small will be enough</label>
            <input class="radioInput" type="radio" name="dimension" value="true" id="dimensionSmall">
            <label for="dimensionBig">Big please</label>
            <input class="radioInput" type="radio" name="dimension" value="false" id="dimensionBig">
        </fieldset>

        <fieldset>
            <div id="newRegExpPlease"> </div>
        </fieldset>

        <fieldset>
            <!-- Allow form submission with keyboard without duplicating the dialog button -->
            <input type="submit" tabindex="-1" style="position:absolute; top:-1000px">
        </fieldset>
    </form>
</div>

<button id="createRegExp" >New expression</button>

